language: python
cache: pip
python:
  - "3.8"

# command to install dependencies
install:
  - pipenv install --system --deploy --ignore-pipfile --dev

# command to run tests
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then nosetests --with-coverage tests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then nosetests --with-coverage tests tests_non_pr; fi'

after_success:
  - coveralls

