language: python
cache: pip
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -e .[testing]

# command to run tests
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then nosetests --with-coverage tests_non_pr tests  else nosetests --with-coverage tests fi

after_success:
  - coveralls

