language: python
cache: pip
python:
  - "3.9"

# command to install dependencies
install:
  - pipenv install --system --deploy --ignore-pipfile --dev

# command to run tests
script:
  - make check
  - make coverage

after_success:
  - coveralls

