version: "3"

volumes:
  giru-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/Giru/data

services:
  duckdns-updater: #https://docs.linuxserver.io/images/docker-duckdns
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/London
      - SUBDOMAINS=giru
      - TOKEN=${duckDnsToken}
    restart: unless-stopped

  giru:
    build:
      context: .
    env_file: .env
    volumes:
      - giru-data:/home/GiruData:rw
    restart: unless-stopped
