version: "3"

volumes:
  giru-data: ~/giru-dev-data


services:
  giru:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - giru-data:/home/GiruData:rw
