from os import getenv

SPOTIPY_CLIENT_ID = getenv('SPOTIPY_CLIENT_ID')
SPOTIPY_CLIENT_SECRET = getenv('SPOTIPY_CLIENT_SECRET')
OMDB_API_KEY = getenv('OMDB_API_KEY')
TELEGRAM_TOKEN = getenv('TELEGRAM_TOKEN')
