""" Using this file to save data. """

julien = [
    'https://media.wmagazine.com/photos/59f1031ad473f932b6e964c5/4:3/w_1536/JULIEN_WMAG_37342.jpg',
    'https://f4.bcbits.com/img/a4215132093_10.jpg',
    'https://static01.nyt.com/images/2017/10/23/arts/23BAKER1/23BAKER1-superJumbo.jpg',
    'http://thebaybridged.com/wp-content/uploads/2017/02/Julien-Baker-at-GAMH-for-Noise-Pop-25-by-Ian-Young-03.jpg',
    'https://www.out.com/sites/out.com/files/2016/03/23/julien-baker-750.jpg',
    'http://static1.1.sqspcdn.com/static/f/828259/27325798/1478651908163/julienbaker1464753676527.png?token=VcH82OrcSIGKNKA1NYO%2FmIiHz2Y%3D',
    'http://diymag.com/media/img/Artists/J/Julien-Baker/Primavera-2016/_1500xAUTO_crop_center-center_75/Julien-Baker-Primavera-2016-20160602-Emma-Swann-7535.jpg',
    'https://static.stereogum.com/uploads/2017/10/julien_jleiby_001-1-1508858086-1498x1000.jpg',
    'http://pixel.nymag.com/imgs/daily/vulture/2015/10/19/19-julien-baker.w750.h560.2x.jpg',
    'http://thefader-res.cloudinary.com/private_images/w_760,c_limit,f_auto,q_auto:eco/170816_JulienBaker_3821_WEB_zmieth/julien-baker-turn-out-the-lights-sprained-ankle-interview.jpg',
    'http://img2-ak.lst.fm/i/u/arO/9874c6ba6183ca27e9fcd56a6586c812',
    'http://diymag.com/media/img/Artists/J/Julien-Baker/05-06-17-Bush-Hall/_1500xAUTO_crop_center-center_75/20170605213357-Julien-Baker-Ph-CFaruolo.jpg',
    'https://video-images.vice.com/articles/57a20706078424ded0752f90/lede/1484861775120-JulienBaker_2.jpeg',
    'https://static01.nyt.com/images/2017/10/23/arts/23BAKER2/23BAKER2-master1050.jpg',
    'https://media.timeout.com/images/104096730/image.jpg',
    'http://78.media.tumblr.com/fdc4c379d25706484d969fe8c071325e/tumblr_p0e062V4hD1wx5fb8o3_1280.jpg',
    'http://thumbnails.cbsig.net/CBS_Production_News_VMS/810/43/SATMO_JulienBaker_Televangelist.jpg',
    'http://www.brooklynvegan.com/files/2016/09/julien-baker-mhow-51.jpg',
    'https://i.ytimg.com/vi/Ys44K0_jZDI/maxresdefault.jpg',
    'https://indiespot.es/wp-content/uploads/2017/01/Julien-Baker.jpg',
    'http://www.trbimg.com/img-5a32d858/turbine/la-et-ms-julien-baker-20171213',
    'http://images.equipboard.com/uploads/source/image/32838/10848528_428997167253207_1312835545940667173_o.jpg?v=1458927234',
    'http://thebaybridged.com/wp-content/uploads/2017/02/Julien-Baker-at-GAMH-for-Noise-Pop-25-by-Ian-Young-02.jpg',
    'http://78.media.tumblr.com/119f3138c6bfe5e79e294eb287d4d0d3/tumblr_obokdgCXcP1r7o2e7o5_1280.jpg'
]

ayuda = {
    'vociao': {
        'Devuelve el mensaje en mayusculas.': '/vociao [mensaje]',
    },
    'saved': {
        'Muestra los mensajes guardados.': '/saved'
    },
    'spotify': {
        'Trae el link de spotify de la cancion indicada y un preview de 30 segundos (si existe).': '/spotify [cancion]'
    },
    'ayuda': {
        'Muestra los comandos y mensajes que se pueden utilizar.': '/ayuda'
    },
    'padondehoy': {
        'Te dice lo que vamos a hacer hoy.': '/padondehoy'
    },
    'cartelera': {
        'Trae una lista de las películas que están en los cines actualmente.': '/cartelera'
    }
}

days = [
    # Lunes
    ["Es lunes mi loco, vete pa' tu casa.",
     "Duermete manin"],
    # Martes
    ["Los martes hay 2x1 en pizza hut, aprovecha.",
     "Orgia en casa del que hable"],
    # Miercoles
    ["Miercoles de cerveza, pero en tu casa tranquilo."],
    # Jueves
    ["Lo jueve nama hay lio en la calle.",
     "2x1 en el cine manin"],
    # Viernes
    ["Es viernes, hoy toca jumo en la zona :D",
     "algo?"],
    # Sabado
    ["Pal' diablo, que se yo man.",
     "Sabado de pilita",
     "Cueros en el jacuzzi"],
    # Domingo
    ["Hoy hay iglesia, maldito impio.", "IGLESIIIIAAA"]
]

replies = [
    'No sé que dijiste, pero maricons ute.',
    'Todo el mundo aquí sabe quien es el mamaguebo.',
    'Soy un maldito bot, no sé que dices!',
    'DAME BANDA!!',
    'No me de reply maricons',
    'No sé que dices',
    '?',
    'Qué?',
    'Ok'
]

mmg = [
    'mmg', 'mamaguevo', 'mamabuego', 'mamaguebo',
    'mamagrano', 'MMG!', 'MMG UTE!', 'M M G', 'MMÑ',
    'mamañema', 'MAMAÑEMA!', 'Un buen mamaguebo!',
    'MA MA GUE BA SO', 'PERO MAMAGRANO!', 'MAMAAAAAGGGUUUUUUUEEEBO!',
    'Mi loco no e por na pero que mmg', 'Diablo si que mmg',
    'El mmg e ute en verdad', 'mmg pero por que',
    'Pa mi ute lo que e un buen mamaguebo',
    'Nunca habia conocido a alguien asi, que maldito mamaguebo',
    'Pero que mmg', 'm a m a g u e b o', 'm a m a g r a n o',
    'm a m a ñ e m a', 'Mejor me pego un tiro antes de criar tal mamaguebo', 'TU MALDITA MADRE MAMAGUEBO TO!',
    'TU MALDITA MADRE', 'MAMAGRANO TO!', 'TU MALDITA MADRE MAMAÑEMA TO!',
    'TU LO QUE ERE UN BUEN MAMAGUEBO !', 'TU LO QUE ERE UN BUEN MAMAGRANO!',
    'TU LO QUE ERE UN BUEN MAMAÑEMA!', 'TMM MMG', 'Pero por favor... buen mamaguebo!',
    'Digame de que vale ser tan mamaguebo?', 'Hagame el favor y ahogese con un ripio',
    'Hay que darle una medalla por mamagrano', 'Mamaguebo del año',
    'Quuuuueeeeee maaaaamaaaaaguuuuuuuueeeeebbboo', 'Me parece que usted es un buen mamaguebo',
    'De vez en cuando yo creo que es medio mamaguebo si', 'COÑAZO CHUPESE UN RIPIO',
    'COÑAZO MAMAGRANO', 'COÑAZO MAMAGUEBO', 'COÑAZO MAMAÑEMA', 'No mejor callese y mamese un guebo',
    'Callese mamaguebo!', 'QUE SE CALLE MAMAGUEBO!', 'Una galleta por mamaguebo',
    "Mi loco, yo voy a proceder a meterle un deo por el culo y meneaselo de lao a lao por ta' de mamaguebo",
    'TU == MMG', 'Eso no e na ser mmg', 'Tan mamaguebo', 'Yo te digo, que mmg',
    'Mamaguebo somos todos, calmese', 'Como se puede existir siendo tan mamaguebo',
    'mmg... que vaina', 'Mire pedazo de mierda, ute no e ma que un buen mmg', 'Ni voy a deci na. que mamaguebo',
    'En mi vida mis ojos habian presenciado tal nivel de mamañemismo', 'La vaina e que ute e un buen mmg',
    'Cuidao que la mamañemeria se pega', "Na' man, ute e el mmg. aceptelo",
    'Por si se te olvida: TU LO QUE ERE UN BUEN MAMAGRANO!', 'Jesusantisima que mmg', 'Jesusantisima que mmñ',
    'EL DIAAAAABLO! QUE MAMAGUEBO!', 'maamaguebo maamaguebo maamaguebo',
    'maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo',
    'maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo maamaguebo',
    'si... no... mmg', 'Yo no se mmg', 'coño en serio mmg', 'Que desafine mmg', 'Que hacemos contigo mmg?',
    'Toy harto de decirlo pero que maldito mamaguebo', 'mmg cual e la vaina?', 'si si si... mamañema',
    'Ey! la mala palabra, tu maldita madre', 'Deje su mamañemeria por favor', 'No se puede con eto mamaguebos',
    'Dejese de vaina, mamaguebo ute', 'Eta vaina ta llena de mamaguebos', 'LIBERTÉ! ÉGALITÉ! MAMAGUEBÉ!',
    'niggas be mamaguebos',
    'Si Dios supiera que de la descendencia del hombre iba a surgir tal gran mamaguebo, hubiese abortado a Adam en la primera semana.',
    'Coño deberia aparecer un Hitler que se lamba a to eto mamaguebos',
    'Hey tranquilo amigo, mas chilleo menos mamaguebismo',
    'These violent delight have violent mamaguebos', "Ma' mamaguebo que to' los Lannister juntos",
    'Excuseme la palabra, pero que buen mamaguebo', 'Aveces pienso que soy un mmg tambien, pero como ute ninguno.',
    'Erase una vez en algun pais del mundo un mamaguebo, el mamaguebo mas grande de todos... y ese mamaguebo era usted.',
    'Record Guinness en mamañemismo.',
    'Dicen que uno es lo que come y usted solo come ripio amiga',
    'Por favor, mentenga este espacio 100% MAMAGUEBO FREE. Gracias.', 'Ay pobres incredulos mamaguebos.',
    'Me huele a mamaguebo por aqui.',
    'FELICIDADES! Usted es el mamaguebo 1,000,000. Se haga ganado el premio de: 3 venezolanas de las baratas! Para recibir su premio por favor mande su informacion personal y numero de cuenta a: tmm@girubot.com',
    'FELICIDADES! Usted es el mamaguebo 1,000,000. Se haga ganado el premio de: una maldita galleta tu maldita madre! Para recibir su premio por favor mande su informacion personal y numero de cuenta a: tmm@girubot.com'
]

cposp = [
    "aren't we all?", "indeed", "un buen mmg en verdad",
    "CERTIFIED PIECE OF SHIT BOT", "it's ok fam we'll be alright",
    "nah, you are fine", "Jesus made you that way", "mano ute se merece una fria",
    "*hugs*", "*Giru sits in silence as an act of empathy with your human condition*",
    "yet a bit less shit than yesterday", "no le pare",
    "no le pare, el mundo ta' lleno de mierda", "you trying your best, fam",
    "A good day to listen to Julien Baker",
    "just gotta make it through the day and you'll be fine",
    "quit your jobs, run to the country, start a small life",
    "fuck that shit man", "it don't matter, we are all dead already",
    "pls get laid soon"
]

mepajeo = [
    "suelte eso",
    "baraja",
    "PAJEARSE NO ES PRODUCTIVO. PAJEARSE ES PASAJERO. SOLO LA GENTE QUEDADA PIERDE TIEMPO EN ESO. MALDITA FRACASADA.",
    "pajearse es una mierda, cortarse las venas tho eso ayuda pila",
    "no, mira una mejor idea: cambia el nombre de tu wifi a \"[nombre de vecino] te ta metiendo lo cuerno\"",
    "mejol netflix and chill",
    "negativo líder",
    "de lo mío, mejor buca de Dio'",
    "mmg, ate 15 padre nuestro por ta pensando en mierda plebe",
    "nooooo mano, que papa dio nos castiga",
    "para qué pajearte hoy si puedes hacerlo mañana?",
    "manin eso no deja cualto, ve al super y paga una compra con paja' a ve'",
    "MANIN ESO NO DEJA GENERA GANANCIAS. TAMO EN DINERO, PRODUCIóNNNNNN!!!!!",
    "pajearse es un pecado, te voy a llama' a la policia. no e' relajo'",
    "mejol vamo a meterle e'te guebe a ese culito tuyo, tu va a ve' que riiiico",
    "loco vamo a dano perico",
    "calientamiento global, crisis politica, revuelta social, con to' la vaina que tan pasando usted lo que ta' pensando e' en pajearse?",
    "hahaha la gente se pajea todavía?",
    "nope",
    "no",
    "nah",
    "maricona, vaya y singe con alguien mejor! coooño!",
    "coñazo humano de mierda, uste tiene hoyo pa' recibir **Y DAR** placer",
    "cuidao que eso da coronavirus",
    "no man, eso hace mucho reguero",
    "ahorrate ese queso y singa jevi æl primeræ que aparezca ",
    "overrated as fuck",
    "\"no te pajearas\" deberia ser el 11vo mandamiento coño",
    "podemos ser más creativos de ahí",
    "no nono nonoooooooo",
    "coño pero se te van a desintegrar los genitales",
    "hazte una por cada verso de la biblia que implique que no debe existir una relación de poder donde el hombre esta sobre la mujer",
    "si las pajas generaran energía, manin ute moveria un Tesla hasta la luna",
    "maldito enferma",
    "si te enfocaras más en verte mejor, ahora mismo te tuvieran pajeando sin tene que preguntar",
    "va a seguí?",
    "pa' qué tu me ta preguntando mamaguebo, yo tengo mejores mierda que hacer",
    "`APROVACI0N DE PAJA.... DENEGADA`",
    "`APROVACI0N DE PAJA.... EL SERVICIO ESTA FUERA DE SERVICIO. DEBE MAMERMELO PARA CONTINUAR.`",
    "me vale verga tu maldita madre",
    "semeimpolta!!",
    "queseyo singatumai",
    "verifica con tu bacá",
    "preguntale a tu mamá",
    "preguntale a tu papá",
    "me pongo a menea par de línea en mi codigo fuente mmg?",
    "meh",
    "bueno, la industria del porno es una vaina messed up, consume con cuidado, no apoye plataformas de abuso.",
    "/mepegountiro mmg",
    "coño pa' esto fue que me crearon? diomio llevame ya coño",
    "por favor, a mi hasta verguenza me da existir con este maldito comando",
    "abrete un issue en Github con un maldito comando mejor",
    "utede me deperdician recua de maricone",
    "dale, manda foto",
    "eso e' saludable",
    "positivo",
    "soporto, vamo' a pajearno to'",
    "sí, hoy tocan 7",
    "sí, hoy tocan 2",
    "sí, hoy tocan 15",
    "hoy sí, te lo mereces",
    "haz lo que te de tu maldita gana",
    "a falta de toto, paja",
    "a falta de guebo, paja",
    "dejalo pal lunes que viene",
    "pajearse un jueves es mejor",
    "oh eso no se pregunta",
    "tirame con /julien para darte material",
    "clorox, metete un deito cuando estes en eso, tu va a ve que rico",
    "dale, pero come algo antes",
    "primero hidratate, luego pajeate",
    "tu alguna vez te ha pajeao viendo el atardecer? loco, el final",
    "sería irresponsable no hacerlo",
    "aprovecha ese queso que le tienes a tu jefæ",
    "no se tu pero yo literal ya me toy pajeando ahora mimo",
    "compra un baconator, meteselo y despues cometelo. una delicia. ",
    "lubricate con un chin chin de picante y mayonesa, tu va a ve",
    "30 pechadas, 20 abdominales, 50 sentadillas y 2 pajas. repertir x5",
    "maaaan, las salchichas bbq del bravo. una bacaneria metese esa vaina por el culo. dale con eso",
    "pajeate si tienes más de 3 días sin singar",
    "si estas en hora de trabajo, que te paguen por venirte",
    "espera a que te estes cagando y pajeante, venirse cagando es `100` veces mejor",
    "siempre, en lo que tu ta en eso recuerdale a tus padres que los quieres",
    "excelente, agarra tus fluidos eyaculados y ponlos en una batidad de aguacate con mango",
    "buscate `cuero descalsa comiendo habichuela con dulce`",
    "intenta pajearte con videos de accidentes de carros, pila de emocionante",
    "bebe pila de romo primero",
    "jochy santos prende a uno pila, haste 3 paja a su nombre",
    "ponte a jose luis perales de soundtrack",
    "dale. aprovecha y haste un onlyfans. sacale cash a esas pajas",
    "deja la paja para cuando estas en un tapón, se más productivo con tu tiempo mi lokix",
    "pajeate y de paso pajea a otra gente--- tu mangue, tu novie, un extraño, tu papá, a quien sea",
    "amigue, disfrutece usted misme",
    "así mimo, cariñito pa' su ripio...o popolita, lo que ute tenga",
    "vamo' a eto y tirale par de dickpics a tu prima",
    "jevi jevi, comparte material",
    "espera que te de sed, date pal de shot de cleren, y a pajear se ha dicho",
    "aquí una idea pa' que te prendas: república dominicana comunista",
    "aquí una idea pa' que te prendas: el alfa con toto",
    "aquí una idea pa' que te prendas: un trio con tus dos primeros mangues ever",
    "aquí una idea pa' que te prendas: tu en la cola de motoconcho a las 3a.m. por villa mella",
    "aquí una idea pa' que te prendas: una mujer embarazada no se puede preñar... los panas tampoco",
    "`APROVACI0N DE PAJA.... EXITOSA`"
]

BAD_CONFIG_SECRET_MESSAGE = [
    'DISCULPE HERMANO, TENGO PROBLEMAS PARA ENTENDERLE',
    'ERRORERRORERROERROREERROROEEROROE',
    'NANI?!',
    'PERO NO PUEDE SER QUE SEAN TAN MAMAÑEMA\n**flips table**',
    'DIABLO PERO NI PORQUE YA NO LO TIENE QUE PROGRAMAR',
    '```\nSIGNEMAVIOLATION(69420): MMG OVERFLOW.\nCRITICAL FAILURE...\nShutting down.```'
]
